-- Создание основных сущностей пользователей
CREATE TABLE IF NOT EXISTS "user"
(
    user_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255) NOT NULL,
    registration_date TIMESTAMP    NOT NULL DEFAULT now()
);

-- Тип для пола
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
            CREATE TYPE gender_enum AS ENUM ('M','F','U');
        END IF;
    END
$$;

CREATE TABLE IF NOT EXISTS user_profile
(
    user_id            INT PRIMARY KEY REFERENCES "user" (user_id) ON DELETE CASCADE,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    date_of_birth      DATE,
    gender             gender_enum  NOT NULL DEFAULT 'U',
    contact_number     VARCHAR(20),
    passport_data      TEXT,
    profile_picture    VARCHAR(255),
    preferred_currency VARCHAR(3),
    preferred_language VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS user_social
(
    social_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INT          NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    provider          VARCHAR(50)  NOT NULL,
    social_identifier VARCHAR(100) NOT NULL,
    token             VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "two_factor_auth"
(
    auth_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT         NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    method  VARCHAR(50) NOT NULL,
    secret  VARCHAR(255),
    enabled BOOLEAN     NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS payment_card
(
    card_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INT NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    provider  VARCHAR(50),
    token     VARCHAR(255),
    last_four CHAR(4)
);

CREATE TABLE IF NOT EXISTS loyalty_level
(
    level_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_name         VARCHAR(50)   NOT NULL,
    discount_rate      DECIMAL(5, 2) NOT NULL,
    bookings_threshold INT,
    amount_threshold   DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS loyalty_program
(
    loyalty_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    level_id   INT NOT NULL REFERENCES loyalty_level (level_id)
);

CREATE TABLE IF NOT EXISTS travel_companion
(
    companion_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INT          NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    first_name     VARCHAR(100) NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    date_of_birth  DATE,
    gender         gender_enum  NOT NULL DEFAULT 'U',
    contact_number VARCHAR(20),
    email          VARCHAR(255)
);