-- Объекты размещения и связанные таблицы
CREATE TABLE IF NOT EXISTS property
(
    property_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id            INT          NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    title               VARCHAR(255) NOT NULL,
    description         TEXT,
    property_type       VARCHAR(50),
    cancellation_policy TEXT
);

CREATE TABLE IF NOT EXISTS favorite_property
(
    user_id     INT NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    property_id INT NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, property_id)
);

CREATE TABLE IF NOT EXISTS location
(
    location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INT NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    latitude    DECIMAL(9, 6),
    longitude   DECIMAL(9, 6)
);

CREATE TABLE IF NOT EXISTS property_image
(
    image_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INT NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    url         VARCHAR(255),
    description TEXT
);

CREATE TABLE IF NOT EXISTS amenity
(
    amenity_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS property_amenity
(
    property_id INT NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    amenity_id  INT NOT NULL REFERENCES amenity (amenity_id) ON DELETE CASCADE,
    PRIMARY KEY (property_id, amenity_id)
);

CREATE TABLE IF NOT EXISTS room
(
    room_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id INT NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    room_number VARCHAR(50),
    room_type   VARCHAR(50),
    price       DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS room_availability
(
    availability_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         INT     NOT NULL REFERENCES room (room_id) ON DELETE CASCADE,
    date_from       DATE    NOT NULL,
    date_to         DATE    NOT NULL,
    is_available    BOOLEAN NOT NULL DEFAULT true
);