-- Бронирования, отзывы, платежи, сообщения и уведомления
CREATE TABLE IF NOT EXISTS booking
(
    booking_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    room_id          INT       NOT NULL REFERENCES room (room_id) ON DELETE CASCADE,
    booking_date     TIMESTAMP NOT NULL DEFAULT now(),
    check_in         DATE      NOT NULL,
    check_out        DATE      NOT NULL,
    status           VARCHAR(50),
    special_requests TEXT
);

CREATE TABLE IF NOT EXISTS booking_guest
(
    booking_id INT NOT NULL REFERENCES booking (booking_id) ON DELETE CASCADE,
    guest_id   INT NOT NULL REFERENCES travel_companion (companion_id) ON DELETE CASCADE,
    PRIMARY KEY (booking_id, guest_id)
);

CREATE TABLE IF NOT EXISTS service
(
    service_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL,
    description  TEXT,
    price        DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS booking_service
(
    booking_id INT NOT NULL REFERENCES booking (booking_id) ON DELETE CASCADE,
    service_id INT NOT NULL REFERENCES service (service_id) ON DELETE CASCADE,
    PRIMARY KEY (booking_id, service_id)
);

CREATE TABLE IF NOT EXISTS payment
(
    payment_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     INT       NOT NULL REFERENCES booking (booking_id) ON DELETE CASCADE,
    user_id        INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    payment_method VARCHAR(50),
    payment_status VARCHAR(50),
    payment_date   TIMESTAMP NOT NULL DEFAULT now(),
    amount         DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS review
(
    review_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  INT UNIQUE REFERENCES booking (booking_id) ON DELETE CASCADE,
    user_id     INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    property_id INT       NOT NULL REFERENCES property (property_id) ON DELETE CASCADE,
    review_text TEXT,
    rating      DECIMAL(2, 1),
    review_date TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS message
(
    message_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id   INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    receiver_id INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    booking_id  INT REFERENCES booking (booking_id) ON DELETE CASCADE,
    content     TEXT,
    sent_date   TIMESTAMP NOT NULL DEFAULT now(),
    is_read     BOOLEAN   NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS notification
(
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT       NOT NULL REFERENCES "user" (user_id) ON DELETE CASCADE,
    message         TEXT,
    type            VARCHAR(50),
    sent_date       TIMESTAMP NOT NULL DEFAULT now(),
    is_read         BOOLEAN   NOT NULL DEFAULT false
);